import { ConfigProvider } from 'antd';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@/src/1app/css/globals.css';
import { antdTheme } from '@/src/1app/theme';

import { AntdRegistry } from '@ant-design/nextjs-registry';

const pretendardFont = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendardFont.variable}`}>
      <body className={pretendardFont.className}>
        <AntdRegistry>
          <ConfigProvider theme={antdTheme}>{children}</ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
